import React, { useState } from "react";
import { Link } from "react-router-dom";
import {
  Rocket,
  BookOpen,
  Code2,
  Video,
  ClipboardCheck,
  ChevronRight,
  Sparkles,
  BarChart2,
  Users,
  Lightbulb,
} from "lucide-react";
import { Button } from "../components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "../components/ui/card";
import { Input } from "../components/ui/input";
import { useTheme } from "../lib/hooks/useTheme";
import CourseCrafterLogo from "../components/CourseCrafterLogo";
import AchievementBadge from "../components/CourseDashboard/AchievementBadge";

/**
 * HomePage - Landing page for CourseCrafter
 */
export const HomePage = () => {
  const { theme, toggleTheme } = useTheme();
  const [email, setEmail] = useState("");

  // Features list
  const features = [
    {
      icon: <Sparkles className="h-6 w-6" />,
      title: "AI-Powered Courses",
      description:
        "Get personalized learning paths generated by our advanced AI",
    },
    {
      icon: <BookOpen className="h-6 w-6" />,
      title: "Interactive Lessons",
      description: "Engage with videos, coding exercises, and quizzes",
    },
    {
      icon: <BarChart2 className="h-6 w-6" />,
      title: "Progress Tracking",
      description: "Monitor your learning journey with detailed analytics",
    },
    {
      icon: <Users className="h-6 w-6" />,
      title: "Community Learning",
      description: "Join discussions and learn with others",
    },
    {
      icon: <Code2 className="h-6 w-6" />,
      title: "Hands-on Coding",
      description: "Practice directly in our built-in code editor",
    },
    {
      icon: <Lightbulb className="h-6 w-6" />,
      title: "Smart Recommendations",
      description: "Get suggestions based on your learning patterns",
    },
  ];

  // Example courses
  const courses = [
    {
      title: "Python Fundamentals",
      description: "Learn Python from scratch with hands-on exercises",
      icon: <Code2 className="h-8 w-8" />,
      category: "Programming",
    },
    {
      title: "Web Development",
      description: "Build modern websites with HTML, CSS, and JavaScript",
      icon: <Code2 className="h-8 w-8" />,
      category: "Web Dev",
    },
    {
      title: "Data Science",
      description: "Introduction to data analysis and visualization",
      icon: <BarChart2 className="h-8 w-8" />,
      category: "Data",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-800">
      {/* Navigation */}
      <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
        <div className="flex items-center space-x-2">
          <CourseCrafterLogo className="h-8 w-8" />
          <span className="text-xl font-bold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
            CourseCrafter
          </span>
        </div>
        <div className="flex items-center space-x-4">
          <Button variant="ghost" asChild>
            <Link to="/login">Sign In</Link>
          </Button>
          <Button asChild>
            <Link to="/generate">Get Started</Link>
          </Button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 md:py-24 text-center">
        <h1 className="text-4xl md:text-6xl font-bold max-w-3xl mx-auto mb-6">
          Craft Your Perfect <span className="text-primary">Learning Path</span>
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto mb-10">
          AI-powered personalized courses tailored to your goals, pace, and
          learning style.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center max-w-lg mx-auto mb-16">
          <Button size="lg" className="flex-1" asChild>
            <Link to="/generate">
              Create Your Course <ChevronRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
          <Button size="lg" variant="outline" className="flex-1" asChild>
            <Link to="/explore">Explore Courses</Link>
          </Button>
        </div>

        <div className="relative max-w-4xl mx-auto rounded-xl overflow-hidden border border-gray-200 dark:border-gray-700 shadow-xl">
          <div className="relative aspect-video">
            <img
              src="/HomePage.png"
              alt="CourseCrafter Learning Interface"
              className="absolute inset-0 w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-purple-600/20 dark:from-primary/30 dark:to-purple-600/30"></div>
            <div className="relative z-10 h-full flex items-center justify-center text-center p-8">
              <div className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm rounded-xl p-6 max-w-2xl">
                <BookOpen className="h-12 w-12 mx-auto mb-4 text-primary" />
                <h3 className="text-xl font-semibold">
                  Interactive Learning Interface
                </h3>
                <p className="text-gray-600 dark:text-gray-300 mt-2">
                  Personalized courses with videos, coding exercises, and
                  quizzes
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="container mx-auto px-6 py-16 bg-white dark:bg-gray-900/50 rounded-t-3xl">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2 className="text-3xl font-bold mb-4">Why Choose CourseCrafter?</h2>
          <p className="text-gray-600 dark:text-gray-300">
            Our platform adapts to your unique learning needs, making education
            more effective and enjoyable.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <Card key={index} className="hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center space-x-4 space-y-0">
                <div className="p-2 rounded-lg bg-primary/10 text-primary">
                  {feature.icon}
                </div>
                <CardTitle>{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-600 dark:text-gray-300">
                  {feature.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Course Showcase */}
      <section className="container mx-auto px-6 py-16">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2 className="text-3xl font-bold mb-4">Popular Course Topics</h2>
          <p className="text-gray-600 dark:text-gray-300">
            Explore our most popular course categories or create your own custom
            learning path.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {courses.map((course, index) => (
            <Card key={index} className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <div className="p-2 rounded-lg bg-primary/10 text-primary w-max mb-4">
                  {course.icon}
                </div>
                <CardTitle>{course.title}</CardTitle>
                <CardDescription>{course.description}</CardDescription>
              </CardHeader>
              <CardFooter>
                <Button variant="outline" className="w-full" asChild>
                  <Link
                    to={`/explore?category=${course.category.toLowerCase()}`}
                  >
                    Explore {course.category} Courses
                  </Link>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      </section>

      {/* Achievement Showcase */}
      <section className="container mx-auto px-6 py-16 bg-gray-50 dark:bg-gray-800/50 rounded-3xl">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Gain Recognition</h2>
          <p className="text-gray-600 dark:text-gray-300">
            Earn achievements as you progress through your learning journey.
          </p>
        </div>
        <div className="flex flex-wrap justify-center gap-6 mb-12">
          <AchievementBadge
            title="Fast Learner"
            description="Completed a course in record time"
            type="speed"
            tier="silver"
            unlocked={true}
            small={false}
          />
          <AchievementBadge
            title="Perfect Score"
            description="Scored 100% on all quizzes in a module"
            type="perfect"
            tier="gold"
            unlocked={false}
            small={false}
          />
          <AchievementBadge
            title="7-Day Streak"
            description="Learned for 7 consecutive days"
            type="streak"
            tier="bronze"
            unlocked={true}
            small={false}
          />
          <AchievementBadge
            title="Course Master"
            description="Completed all courses in a category"
            type="mastery"
            tier="platinum"
            unlocked={false}
            small={false}
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-6 py-24 text-center">
        <div className="bg-gradient-to-r from-primary to-purple-600 rounded-3xl p-12 text-white">
          <Rocket className="h-12 w-12 mx-auto mb-6" />
          <h2 className="text-3xl font-bold mb-4">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl mb-8 max-w-2xl mx-auto">
            Join thousands of learners who are achieving their goals with
            CourseCrafter.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center max-w-lg mx-auto">
            <Input
              type="email"
              placeholder="Enter your email"
              className="bg-white/20 border-white/30 text-white placeholder-white/70 flex-1"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Button size="lg" variant="secondary" className="whitespace-nowrap">
              Get Started
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <CourseCrafterLogo className="h-6 w-6 text-white" />
                <span className="text-white font-bold">CourseCrafter</span>
              </div>
              <p className="text-sm">
                AI-powered personalized learning platform to help you master any
                subject.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-4">Product</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/features" className="hover:text-white">
                    Features
                  </Link>
                </li>
                <li>
                  <Link to="/pricing" className="hover:text-white">
                    Pricing
                  </Link>
                </li>
                <li>
                  <Link to="/examples" className="hover:text-white">
                    Examples
                  </Link>
                </li>
                <li>
                  <Link to="/updates" className="hover:text-white">
                    Updates
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-white font-medium mb-4">Resources</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/blog" className="hover:text-white">
                    Blog
                  </Link>
                </li>
                <li>
                  <Link to="/tutorials" className="hover:text-white">
                    Tutorials
                  </Link>
                </li>
                <li>
                  <Link to="/support" className="hover:text-white">
                    Support
                  </Link>
                </li>
                <li>
                  <Link to="/docs" className="hover:text-white">
                    Documentation
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-white font-medium mb-4">Company</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/about" className="hover:text-white">
                    About
                  </Link>
                </li>
                <li>
                  <Link to="/careers" className="hover:text-white">
                    Careers
                  </Link>
                </li>
                <li>
                  <Link to="/contact" className="hover:text-white">
                    Contact
                  </Link>
                </li>
                <li>
                  <Link to="/press" className="hover:text-white">
                    Press
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-sm text-center">
            © {new Date().getFullYear()} CourseCrafter. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
